/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Formularios;

import Conexiones.ConexionDB;
import Conexiones.consultas;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author juann
 */
public class catalogoCuenta extends javax.swing.JPanel {

    /**
     * Creates new form Transaccion
     */
    public catalogoCuenta() {
        initComponents();
        catalogoCuentas();//MANDA A LLAMAR EL METODO EN EL CONSTRUCTOR PARA QUE CUANDO SE INICIALICE SE EJECUTE
    }
    //METODO QUE MANDA A LLAMAR DE LA BD EL CATALOGO DE CUENTAS Y LO MUESTRA EN LA TABLA CORRESPONDIENTE
    public void catalogoCuentas() {
        ConexionDB db = new ConexionDB();
        Connection cn = db.conectar();
        try {
            PreparedStatement pst = cn.prepareStatement("SELECT * FROM catalogocuentas");
            ResultSet resultado = pst.executeQuery();
            DefaultTableModel modeloTabla = new DefaultTableModel();
            modeloTabla.addColumn("Código");
            modeloTabla.addColumn("Cuenta");
            while (resultado.next()) {
                int codigo = resultado.getInt("codigo"); // Reemplaza "codigo" con el nombre de tu columna.
                String cuenta = resultado.getString("cuenta"); // Reemplaza "cuenta" con el nombre de tu columna.
                modeloTabla.addRow(new Object[]{codigo, cuenta});
                jTable1.setModel(modeloTabla); // Reemplaza "jTable1" con el nombre de tu JTable.
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setToolTipText("");
        setPreferredSize(new java.awt.Dimension(1150, 650));

        jPanel1.setName("aa"); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 680));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Ink Free", 0, 36)); // NOI18N
        jLabel1.setText("CATALOGO DE CUENTAS DE AGORA S.A");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 1010, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
